# Generated by Django 3.0.5 on 2020-07-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_message', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
