# Generated by Django 3.0.5 on 2020-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL link')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('main_product_image', models.ImageField(upload_to='products')),
                ('addtional_image_1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('addtional_image_2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('addtional_image_3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('addtional_image_4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('addtional_image_5', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
